# Generated by Django 5.2.9 on 2025-12-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("filesize", models.CharField(default=".9mb", max_length=20)),
                ("close", models.BooleanField(default=False)),
                ("tag_color", models.CharField(default="green", max_length=20)),
                ("tag_title", models.CharField(default="Download Now", max_length=50)),
                ("is_tag_open", models.BooleanField(default=True)),
            ],
        ),
    ]
